export const metadata = { title: "Terms of Service" }

export default function TermsPage() {
  return (
    <>
      <h1>Terms of Service</h1>
      <p>Last updated: August 26, 2026</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of this platform (the
        &quot;Service&quot;). By creating an account or signing in, you confirm that you have
        read, understood, and agree to be bound by these Terms. If you do not agree, do not use
        the Service.
      </p>

      <h2>1. What the Service is</h2>
      <p>
        The Service is a tool that lets you build, configure, and run automated AI agents using
        your own instructions, your own third-party accounts (such as email, messaging, and SMS
        services), and your own AI provider API keys. <strong>You</strong> decide what your
        agents do. <strong>You</strong> write their instructions. <strong>You</strong> connect
        the accounts they act through.
      </p>

      <h2>2. You are responsible for your agents</h2>
      <ul>
        <li>
          Agents act on your behalf, under instructions you wrote. Every action an agent takes  - 
          every email sent, message posted, SMS delivered, or reply generated  -  is your action
          and your responsibility.
        </li>
        <li>
          AI models are probabilistic. They can misread instructions, produce incorrect or
          inappropriate output, act on the wrong message, or behave in ways you did not intend.
          You accept this risk when you put an agent live.
        </li>
        <li>
          <strong>You must test every agent before publishing it</strong>, and re-test it after
          changing its instructions. The Service provides test runs for exactly this purpose.
          Publishing an untested agent is entirely at your own risk.
        </li>
        <li>
          You are responsible for monitoring your agents while they are live and for pausing or
          deleting any agent that misbehaves.
        </li>
      </ul>

      <h2>3. Third-party accounts and costs</h2>
      <ul>
        <li>
          You connect your own accounts (Gmail, Telegram, Twilio, OpenAI, Anthropic, and others).
          You are responsible for complying with each provider&apos;s terms of service.
        </li>
        <li>
          AI model usage, SMS fees, and any other third-party charges incurred by your agents are
          billed by those providers to you. Spending limits offered by the Service are a
          convenience, not a guarantee  -  you remain responsible for all charges on your accounts.
        </li>
        <li>
          You are responsible for keeping your API keys and credentials valid and secure, and for
          revoking them if you stop using the Service.
        </li>
      </ul>

      <h2>4. Acceptable use</h2>
      <p>
        You may not use the Service to send spam, harass people, violate any law, infringe
        anyone&apos;s rights, or automate activity that a connected provider prohibits. We may
        suspend or terminate accounts that do.
      </p>

      <h2>5. The Service is provided &quot;AS IS&quot;</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot;, WITHOUT WARRANTY
        OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF
        MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, RELIABILITY, OR
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE,
        OR SECURE, THAT SCHEDULED RUNS WILL EXECUTE ON TIME OR AT ALL, OR THAT ANY AGENT WILL
        BEHAVE AS YOU INTENDED.
      </p>

      <h2>6. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS,
        REVENUE, DATA, GOODWILL, OR BUSINESS OPPORTUNITY, ARISING FROM OR RELATED TO YOUR USE OF
        THE SERVICE OR THE CONDUCT OF ANY AGENT YOU CREATED  -  INCLUDING MESSAGES SENT TO THE
        WRONG RECIPIENT, INCORRECT OR HARMFUL CONTENT GENERATED BY AI MODELS, MISSED OR
        DUPLICATED RUNS, THIRD-PARTY CHARGES, OR LOSS OF ACCESS TO CONNECTED ACCOUNTS  -  EVEN IF
        WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR TOTAL AGGREGATE LIABILITY
        FOR ANY CLAIM ARISING FROM THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU
        PAID US FOR THE SERVICE IN THE TWELVE MONTHS PRECEDING THE CLAIM, OR TEN DOLLARS ($10)
        IF YOU HAVE PAID NOTHING.
      </p>

      <h2>7. Indemnification</h2>
      <p>
        You agree to indemnify and hold us harmless from any claim, demand, loss, or expense
        (including reasonable legal fees) arising from your agents&apos; actions, your breach of
        these Terms, or your violation of any law or third-party right.
      </p>

      <h2>8. Changes and termination</h2>
      <p>
        We may modify the Service or these Terms at any time. Continued use after changes take
        effect constitutes acceptance. You may stop using the Service and delete your account at
        any time; we may suspend or terminate access for breach of these Terms.
      </p>

      <h2>9. Contact</h2>
      <p>Questions about these Terms can be sent to the workspace administrator.</p>
    </>
  )
}
